apiVersion: v1
kind: Namespace
metadata:
  name: facele
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: facele-network-policy
  namespace: facele
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 4848
  egress:
  - to:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 8080  # Services internos