apiVersion: v1
kind: ConfigMap
metadata:
  name: facele-config
data:
  facele.properties: |
      # Configuraci\u00f3n general com\u00fan de los servicios "facele_ws", "facele_qp" y "facele_qw"
      #test desde yaml
      # Puerto TCP que se bloquar\u00e1 para evitar m\u00faltiples instancias del servicio.
      # Si se ejecutan en la misma m\u00e1quina QP y QW, deber\u00e1 ser diferente del puerto bloqueado
      # por la cola "facele_qw"
      lockedPortQW = 5555

      # Puerto TCP que se bloquar\u00e1 para evitar m\u00faltiples instancias del servicio.
      # Si se ejecutan en la misma m\u00e1quina QP y QW, deber\u00e1 ser diferente del puerto bloqueado
      # por la cola "facele_qp"
      lockedPortQP = 5556

      # Tama\u00f1o m\u00e1ximo (en kB) de cada archivo .log, antes de cerrarlo y rotar
      logSize=2048

      # Driver JDBC para acceder a la base de datos. Solo para colas, no para WS.
      jdbcDriver=org.postgresql.Driver

      # URL de la base de datos. El programa solo establece una conexi\u00f3n. Solo para colas, no para WS.
      jdbcUrl=jdbc:postgresql://server:5432/facele_tpf

      # Usuario que interact\u00faa con la base de datos, leyendo la cola y las tablas
      # de referencia. Solo para colas, no para WS.
      jdbcUser=sa

      #Contrase\u00f1a del usuario JDBC para leer la cola y las tablas de referencia.
      #  Solo para colas, no para WS.
      jdbcPassword=Free09

      # Nombre del recurso JDNDI para acceder a la base de datos. Solo WS
      jndiResource=jdbc/facele_tpf

      # Directorio con templates JASPER. Solo QP
      templateDir=./templates/

      # Directorio ra\u00edz donde se almacenar\u00e1n los documentos generados.
      # Si el par\u00e1metro "pdfTemplateName" contiene directorios, se construir\u00e1n
      # a la medida que se necesiten, cre\u00e1ndose el \u00e1rbol autom\u00e1ticamente.
      # Este directorio puede ser una carpeta local, un enlace simb\u00f3lico, un punto
      # de montaje, o una carpeta dentro de un bucket S3 (Minio)
      # Para almacenamiento basado en el filesystem, puede ser un punto relativo
      # a "<GLASSFISH>/domains/domain1/config", o absoluto.
      # Para almacenamiento basado en S3, es un directorio desde la ra\u00edz del bucket
      # Solo QP y WS.
      # Ejemplo de directorio relativo del filesystem
      # pdfDir=./pdfs/
      # Ejemplo de un directorio absoluto del filesystem
      # pdfDir=/pdfs/
      # Ejemplo de un directorio dentro del bucket S3
      pdfDir=pdfs

      # Formato del nombre del archivo generado por cada documento fiscal.
      # Puede definir nuevos subdirectorios que se crear\u00e1n on-demand.
      # Si define subdirectorios, utilice "/" como separador.
      # Puede incluir Los siguientes comodines: 
      # @HASH: C\u00f3digo pseudo-aleatorio para la identificaci\u00f3n segura de comprobantes 
      # generados. Si a\u00fan no tiene hash, toma el valor "UNKNOWN_HASH________"
      # S\u00f3lo letras "A" a "Z" y d\u00edgitos "0" a "9". 20 caracteres.
      # @CUIT: CUIT del emisor (empresa propia). 11 d\u00edgitos num\u00e9ricos, sin guiones
      # @TIPOCOMP: n\u00famero de tipo de comprobante, seg\u00fan ARCA. 3 d\u00edgitos, con 
      # ceros a la izquierda
      # @PTOVTA: n\u00famero de punto de venta. 5 d\u00edgitos num\u00e9ricos. Ceros a la izquierda.
      # Si el comprobante a\u00fan no fue autorizado, toma el valor ""
      # @NROCOMP: n\u00famero de comprobante. Si es un rango, primero del rango. 8 d\u00edgitos
      # num\u00e9ricos, con ceros a la izquierda. 
      # Si el comprobante a\u00fan no fue autorizado, toma el valor "00000000"
      # @SINTETICO: representaci\u00f3n sint\u00e9tica del tipo de comprobante, tal como figura
      # en la tabla facele.t_FECbteTipos
      # @LETRAFISCAL: letra fiscal (A, B, C, M, E) tal como figura en la tabla 
      # facele.t_FECbteTipos
      # @TIPODOC: n\u00famero de tipo de documento del receptor, tal como lo codifica ARCA.
      # Tres d\u00edgitos num\u00e9ricos, con ceros a la izquierda.
      # @NRODOC: n\u00famero de documetno de identificaci\u00f3n del receptor. 11 d\u00edgitos num\u00e9ricos,
      # con ceros a la izquierda. Si es un documento innominado, toma el valor ""
      # @IDDOCUMENTO: c\u00f3digo interno del documento. Ocho d\u00edgitos num\u00e9ricos, con ceros
      # a la izquierda.
      # Cuando se realizan simulaciones de comprobantes, es importante agregar el tag
      # @IDDOCUMENTO en el nombre del archivo, para evitar sobreescrituras en caso
      # de simular varios del mismo tipo, porque el n\u00famero de comprobante a\u00fan no est\u00e1
      # asignado durante la simulaci\u00f3n
      # Solo QP, porque WS lee desde la tabla de comprobantes, el nombre del archivo
      pdfNameTemplate=@CUIT/@SINTETICO-@LETRAFISCAL-@PTOVTA-@NROCOMP_@IDDOCUMENTO.pdf

      # Endpoint donde la cola notificar\u00e1 que termin\u00f3 de generar un lote de 
      # comprobantes. Si se omite, no se notificar\u00e1.
      # Solo QP
      # batchDoneEndpointQP=http://serve:8086/api/ProcesosInternos/Facele/qw-notification

      # Endpoint donde la cola notificar\u00e1 que termin\u00f3 de autorizar un lote de 
      # comprobantes. Si se omite, no se notificar\u00e1.
      # Solo QW
      # batchDoneEndpointQW=http://server:8086/api/ProcesosInternos/Facele/qw-notification


      # IP o nombre del servidor proxy con ARCA (opcional). QW y WS
      # ProxyHost=beta

      # Puerto TCP del servidor proxy ARCA (opcional). QW y WS
      # ProxyPort=3128

      # Endpoint del web-service ARCA de autenticaci\u00f3n. Puede apuntar al servidor de 
      # homologaci\u00f3n o al de producci\u00f3n.
      # Requerido para la solicitud del ticket.
      WSAAEndpoint=https://wsaahomo.afip.gov.ar/ws/services/LoginCms
      #WSAAEndpoint=https://wsaa.afip.gov.ar/ws/services/LoginCms

      # Endpoint del web-service de facturaci\u00f3n electr\u00f3nica v1. 
      # Puede apuntar al servidor de homologaci\u00f3n o al de producci\u00f3n.
      WSFEEndpoint=https://wswhomo.afip.gov.ar/wsfev1/service.asmx
      #WSFEEndpoint=https://servicios1.afip.gov.ar/wsfev1/service.asmx

      # Endpoint del web-service de Constataci\u00f3n de comprobantes. 
      # Puede apuntar al servidor de homologaci\u00f3n o al de producci\u00f3n.
      WSCDCEndpoint=https://wswhomo.afip.gov.ar/WSCDC/service.asmx
      #WSCDCEndpoint=https://servicios1.afip.gov.ar/WSCDC/service.asmx

      # Endpoint del web-service de facturaci\u00f3n electr\u00f3nica de exportaci\u00f3n v1. 
      # Puede apuntar al servidor de homologaci\u00f3n o al de producci\u00f3n.
      WSFEXEndpoint=https://wsfe-homo.arca.gob.ar/wsfexv1/service.asmx
      #WSFEXEndpoint=https://servicios1.afip.gov.ar/wsfexv1/service.asmx

      # Nivel de depuraci\u00f3n: 0 o 1
      # Cuando el nivel es 1, se vuelca en stdout informaci\u00f3n de depuraci\u00f3n del tr\u00e1fico con el webservice
      DebugLevel=1

      # Timeout general de conexi\u00f3n y ejecuci\u00f3n al web-service ARCA, en milisegundos
      WSTimeout=20000

      # CUIT empleado en operaciones gen\u00e9ricas de consultas en ARCA, especialmente
      # las recuperaciones de tablas de referencia. Debe existir un certificado v\u00e1lido
      # para este CUIT, de manera que puede generar un ticket.

      # Gustavo Sbrugnera - monotributo
      #GenericCUIT=20216330847
      # Cabrera Jos\u00e9 Luis
      #GenericCUIT=20175468790
      # OCA Log SA
      GenericCUIT=30717024393


      # Lista de IDs de puntos de venta que deber\u00e1n atenderse, separados por comas. 
      # Se refiere a los Ids internos tal como se indican en la tabla facele.t_FEPtosVta.IdPtoVta;
      # NO son los c\u00f3digos de puntos de venta seg\u00fan ARCA, como se indican en facele.t_FEPtosVta.PtoVta.
      # La cola QW implementar\u00e1 un Thread para cada uno de ellos.
      #PtosVtaList=1,2,6
      PtosVtaList=1,2,9

      # "true" si el almac\u00e9n de los PDFs se basar\u00e1 en un servidor S3 (Minio, AWS).
      # Si es "false" o se omite, el almac\u00e9n se basa en el filesystem.
      # Solo para WS y QP
      S3Support=true

      # URL del servidor S3, incluido el puerto TCP para APIs, que es diferente el puerto
      # para el browser web del almac\u00e9n
      # Solo para WS y QP
      # S3URL=http://server:9000
      S3URL=http://server:4515

      # Nombre del bucket ra\u00edz del almac\u00e9n. Dentro se crear\u00e1 la carpeta "pdfs" o la
      # que corresponda seg\u00fan el par\u00e1metro "pdfDir"
      # V\u00e9ase https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
      # para conocer las reglas de nombres de buckets
      # Solo para WS y QP
      # S3Bucket=facele
      S3Bucket=test-comprobantes

      # Usuario S3, o "access key" del almac\u00e9n
      # Solo para WS y QP
      # S3User=minioadmin
      S3User=admin

      # Contrase\u00f1a S3, o "secret key" del almac\u00e9n
      # Solo para WS y QP
      # S3Password=minioadmin
      S3Password=tpf12345

      # Cuando es "true", los mensajes de log tambi\u00e9n se redirigen a stdout

      # Predeterminado: "false"

      LogStdout=true